org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
